# docker build -t yzyxdly/demo-nginx:latest --rm ./
FROM nginx
MAINTAINER yzyxdly
LABEL version="1.0" description="demo-nginx"
ADD default.conf /etc/nginx/conf.d/
ADD index.html /usr/share/nginx/html/ 

